### ISSUE TITLE
Abort not cleared in _expose

### ISSUE THREAD

**Issue by tribeiro** [astroufsc/chimera-sbig#1]
in here

https://github.com/astroufsc/chimera_sbig/blame/master/chimera_sbig/instruments/sbig.py#L241

I think abort should be cleared before entering the while loop. Otherwise, if it was set once it may never come back again...

**Comment by phsilva** [comment]
And it is cleared at
https://github.com/astroufsc/chimera/blob/master/src/chimera/instruments/camera.py#L103

You are not supposed to call _expose directly, so Camera.expose does the
job for you.

2015-07-13 15:27 GMT-03:00 Tiago notifications@github.com:

**Comment by wschoenell** [comment]
@tribeiro: Can we close this?

**Comment by tribeiro** [comment]
sure! go ahead...

T.

On Tue, Jul 14, 2015 at 3:39 PM, William Schoenell <notifications@github.com

**Comment by wschoenell** [comment]
Closed #1.
